language: php

php:
        - "5.4"

matrix:
        allow_failures:
                - php: 5.5

script: "VERBOSE=true ./vendor/bin/tester -s tests/ -j 10"

before_script:
        - composer self-update
        - composer install --dev
        - sudo chmod 777 -R ./